### ISSUE TITLE
esp8266 with max31865

### ISSUE THREAD

**Issue by jeanrocco** [olewolf/arduino-max31865#2]
Hello, I'm still not used (yet) to play (understand) with libraries, so I'm just asking if your library is non blocking and would work well with the esp8266 12E. 
Thank's for sharing your "savoir faire" !

**Comment by olewolf** [comment]
It's non-blocking in the sense that it doesn't wait endlessly to return until some response has been received. However, it takes the time to communicate via SPI that a few bytes of SPI communication takes.

I don't see any reason why it might cause any problems in a design that incorporates the ESP8266.

**Comment by jeanrocco** [comment]
Thanks for your answer, after some diggings, and learnings from your code, I modified the elementary "adafruit max31865 library" to be non blocking, meaning no delay of 10 ms after setting "bias on" and no 65 ms delay after setting the "oneshot" bit which starts the conversion, ... it's using millis() now.  I'm using the max31865 with a 1000 ohms rtd and https://github.com/Schm1tz1/ESPressIoT firmware on my esp8266. The temp. sensor works quite well. Thanks again for your sharing.
jrb.
